GEMINI_API_KEY = "AIzaSyCadylsehUrV0Tn1ZQToAUUBUGbZSRQnJo"
GEMINI_BACKUP_API_KEY = "AIzaSyCES3WftikKpOU9VpKw9Jf5tzV-7Bqi7-Q"
IMS_API_KEY = "1a901e45-9028-44ff-bd2c-35e82407fb9b"
DATABASE_URL = "postgresql://neondb_owner:npg_gtWTp2KxDe7Y@ep-broad-fog-aimsm40u-pooler.c-4.us-east-1.aws.neon.tech/neondb?sslmode=require"
CREWAI_TELEMETRY_ENABLED = false
